esoversion: "external-secrets.io/v1"

clusterGroup:
  namespaces:
    golang-external-secrets:
      disabled: true
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets:
